---

# For the unattended install to work as intended (i.e., unattended)
# we must place setupVars.conf into place *before* running the installer
# This means we also need to create the pihole user/group ourselves

- name: "Create {{ pihole.user }} system user and group (nologin shell)"
  ansible.builtin.user:
    name: "{{ pihole.user }}"
    state: present
    system: yes
    shell: /usr/sbin/nologin

# this task requires the pihole.user user/group to exist, fails otherwise
- name: Create Pi-Hole configuration directory
  ansible.builtin.file:
    name: "{{ pihole.path.config }}"
    state: directory
    owner: "{{ pihole.user }}"
    group: "{{ pihole.group }}"
    mode: 0755

- name: Prepare Pi-Hole configuration (first-time installation)
  ansible.builtin.template:
    src: "setupVars.conf.j2"
    dest: "{{ pihole.path.config }}/setupVars.conf"
    owner: "{{ pihole.user }}"
    group: "{{ pihole.group }}"
    mode: 0644
  when: not (pihole_installed | bool)
  notify: reconfigure pihole
