---

- name: Restart Pi-Hole FTL
  ansible.builtin.systemd:
    name: pihole-FTL.service
    state: restarted
  listen: restart pihole-FTL

# rather than restarting the systemd job, use pihole's
# builtin ability to apply changed configuration
- name: Reconfigure Pi-Hole subsystems
  ansible.builtin.command: 
    argv:
      - "/etc/.pihole/automated install/basic-install.sh" 
      - "--reconfigure" 
      - "--unattended"
  listen: reconfigure pihole
