---

- name: Restart Pi-Hole FTL
  ansible.builtin.systemd:
    name: pihole-FTL.service
    state: restarted
  listen: restart pihole-FTL

# rather than restarting the systemd job, use pihole's
# builtin ability to apply changed configuration
- name: Reconfigure Pi-Hole subsystems
  ansible.builtin.command: "{{ pihole.path.bin }}/pihole -r"
  listen: reconfigure pihole

- name: Update desktop entry database
  ansible.builtin.command: >
    /usr/bin/update-desktop-database -v {{ xdg_desktop_entries }}
