---

- name: Restart Pi-Hole DNS resolver
  systemd:
    name: pihole-FTL.service
    state: restarted
  listen: restart pihole-FTL

- name: Update desktop entry database
  ansible.builtin.command: >
    /usr/bin/update-desktop-database -v {{ xdg_desktop_entries }}
